### ISSUE TITLE
`rboot-hex2a.h` is missing?

### ISSUE THREAD

**Issue by pgollor** [kzyapkov/esp-arduino-rboot#1]
Hi,

i try to compile your code but i think there is a problem with your rboot version.
I get the following error after run `make`:

```
rboot/rboot.c:9:25: fatal error: rboot-hex2a.h: No such file or directory
 #include "rboot-hex2a.h"
```

The file is really not there.
Do you know something about this?

Thanks.

**Comment by kzyapkov** [comment]
Oops, sorry, just saw this. Notifications must have slipped by me...

This file is actually generated by the build process inside BUILD_DIR, and the second stage needs to be able to include it as a header.

Please see the documentation by the rboot author, the build process and rboot architecture are very well explained, for which @raburton is to blame.

Also, this code should only serve as an example, things have probably moved significantly with both rboot and the ESP8266 Arduino core. This repo is no longer maintained.
